import {phase2} from './phase2.js';
import {createClient} from '@supabase/supabase-js';
import {z} from 'zod';
export type RequestLike={method?:string;url?:string;headers:Record<string,string|string[]|undefined>;body?:unknown};
export type ResponseLike={status:(status:number)=>ResponseLike;json:(body:unknown)=>void;setHeader:(key:string,value:string)=>void};
const envSchema=z.object({SUPABASE_URL:z.url(),SUPABASE_PUBLISHABLE_KEY:z.string().min(20)});
const bboxSchema=z.tuple([z.number().min(-180).max(180),z.number().min(-90).max(90),z.number().min(-180).max(180),z.number().min(-90).max(90)]).refine(b=>b[0]<b[2]&&b[1]<b[3]);
const reviewSchema=z.object({decision:z.enum(['VERIFIED','REJECTED']),reason:z.string().trim().min(10).max(2000),request_id:z.uuid()});
/** Authenticated adapter. The user's JWT is forwarded so database RLS also applies. */
export async function handle(req:RequestLike,res:ResponseLike,environment:Record<string,string|undefined>){const correlationId=crypto.randomUUID();res.setHeader('Cache-Control','no-store');res.setHeader('X-Correlation-ID',correlationId);const fail=(status:number,code:string,message:string)=>res.status(status).json({success:false,error:{code,message,correlation_id:correlationId}});try{const env=envSchema.safeParse(environment);if(!env.success)return fail(503,'NOT_CONFIGURED','City services are not configured.');const authorization=req.headers.authorization;if(typeof authorization!=='string'||!authorization.startsWith('Bearer '))return fail(401,'AUTH_REQUIRED','Sign in to continue.');const client=createClient(env.data.SUPABASE_URL,env.data.SUPABASE_PUBLISHABLE_KEY,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}});const {data:auth,error:authError}=await client.auth.getUser(authorization.slice(7));if(authError||!auth.user)return fail(401,'INVALID_SESSION','Your session has expired.');const {data:profile}=await client.from('profiles').select('role,is_active').eq('id',auth.user.id).single();if(!profile?.is_active||profile.role==='PUBLIC_USER')return fail(403,'FORBIDDEN','Workspace access is unavailable.');const url=new URL(req.url??'/','https://civicsphere.invalid');const path=url.pathname.replace(/^\/api\//,'').split('/');const phase2Result=await phase2(client,req,path,url);if(phase2Result)return res.status(200).json(phase2Result);if(req.method==='GET'&&path[0]==='issues'&&path[1]==='geojson'){const bounds=bboxSchema.parse((url.searchParams.get('bbox')??'').split(',').map(Number));const severity=z.enum(['CRITICAL','HIGH','MEDIUM','LOW','INFO']).nullable().parse(url.searchParams.get('severity'));const {data,error}=await client.rpc('issues_in_view',{west:bounds[0],south:bounds[1],east:bounds[2],north:bounds[3],severity_filter:severity});if(error)throw error;return res.status(200).json({success:true,data:{type:'FeatureCollection',features:(data??[]).map((i:{id:string;latitude:number;longitude:number;issue_id:string;title:string;severity:string;status:string})=>({type:'Feature',id:i.id,geometry:{type:'Point',coordinates:[i.longitude,i.latitude]},properties:{issue_id:i.issue_id,title:i.title,severity:i.severity,status:i.status}})),limit:100}});}
if(req.method==='POST'&&path[0]==='issues'&&path[2]==='review'){const id=z.uuid().parse(path[1]);const body=reviewSchema.parse(req.body);const {data,error}=await client.rpc('review_issue',{target_id:id,decision:body.decision,review_reason:body.reason,request_id:body.request_id});if(error)throw error;return res.status(200).json(data);}
if(req.method==='GET'&&path[0]==='issues'){let query=client.from('issues').select('*',{count:'exact'});if(path[1])query=query.eq('id',z.uuid().parse(path[1]));const page=z.coerce.number().int().min(0).max(100000).parse(url.searchParams.get('page')??0);const size=z.coerce.number().int().min(1).max(100).parse(url.searchParams.get('limit')??25);const severity=url.searchParams.get('severity');if(severity)query=query.eq('severity',z.enum(['CRITICAL','HIGH','MEDIUM','LOW','INFO']).parse(severity));const {data,error,count}=await query.order('created_at',{ascending:false}).range(page*size,page*size+size-1);if(error)throw error;return res.status(200).json({success:true,data:{items:data,total:count,page,limit:size}});}
return fail(404,'NOT_FOUND','This endpoint is not available.');}catch(error){if(error instanceof z.ZodError)return fail(400,'INVALID_INPUT','Check the supplied fields.');const code=error&&typeof error==='object'&&'code' in error?String(error.code):'';console.error(JSON.stringify({event:'api_error',correlation_id:correlationId,code}));return fail(code==='42501'?403:code==='22023'?409:code==='54000'?429:code==='P0002'?404:500,'COMMAND_FAILED','The operation could not be completed.');}}
